name: 'Rsync Command'
description: ''
inputs:
  source:
    description: 'source directory'
    default: './'
  destination:
    description: 'destination directory'
    default: 22
  remote_shell:
    description: 'remote shell'
    default: 'ssh'
  exclude_default:
    description: 'default exclude params'
    default: ''
  exclude:
    description: 'exclude params'
    default: ''
  parameters:
    description: 'misc params'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - run: rsync -e "${{ inputs.remote_shell }}"  ${{ inputs.parameters }} "${{ inputs.source }}" "${{ inputs.destination }}" ${{ inputs.exclude_default }} ${{ inputs.exclude }}
      shell: bash
